apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: atenex
data:
  # General
  INGEST_LOG_LEVEL: "INFO"

  # Celery
  INGEST_CELERY_BROKER_URL: "redis://redis-service-master.atenex.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service-master.atenex.svc.cluster.local:6379/1"

  # PostgreSQL
  INGEST_POSTGRES_SERVER: "postgresql-service.atenex.svc.cluster.local"
  INGEST_POSTGRES_PORT: "5432"
  INGEST_POSTGRES_USER: "postgres"
  INGEST_POSTGRES_DB: "atenex"
  # INGEST_POSTGRES_PASSWORD -> Secret

  # Milvus/Zilliz
  INGEST_MILVUS_URI: "https://in03-0afab716eb46d7f.serverless.gcp-us-west1.cloud.zilliz.com" # MODIFIED
  INGEST_MILVUS_COLLECTION_NAME: "atenex_collection" #"atenex_e5_collection" 
  INGEST_MILVUS_GRPC_TIMEOUT: "20" # Increased timeout as per consideration for Zilliz Cloud

  # Google Cloud Storage
  INGEST_GCS_BUCKET_NAME: "atenex-01"

  # Embedding Settings
  INGEST_EMBEDDING_DIMENSION: "1536" #"768" 

  # Tokenizer Settings
  INGEST_TIKTOKEN_ENCODING_NAME: "cl100k_base"

  # URLs for dependent services
  INGEST_EMBEDDING_SERVICE_URL: "http://embedding-service.atenex.svc.cluster.local:80/api/v1/embed" #"http://host.docker.internal:8003/api/v1/embed" 
  INGEST_DOCPROC_SERVICE_URL: "http://docproc-service.atenex.svc.cluster.local:80/api/v1/process"