apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-api-deployment
  namespace: atenex
  labels:
    app: ingest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-api
  template:
    metadata:
      labels:
        app: ingest-api
    spec:
      containers:
        - name: ingest-api
          image: ghcr.io/dev-nyro/ingest-service:develop-f6fa2b8 # Placeholder, CI/CD to update
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          command: ["gunicorn"]
          args: ["-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-b", "0.0.0.0:8000", "-t", "120", "--log-level", "info", "app.main:app"]
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets # Reference to the secret
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp-secrets/key.json"
            - name: INGEST_ZILLIZ_API_KEY # MODIFIED: Added Zilliz API Key from Secret
              valueFrom:
                secretKeyRef:
                  name: ingest-service-secrets # Name of the k8s Secret
                  key: ZILLIZ_API_KEY # Key within the Secret
          volumeMounts:
            - name: gcp-key-volume
              mountPath: "/etc/gcp-secrets"
              readOnly: true
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
      volumes:
        - name: gcp-key-volume
          secret:
            secretName: gcs-worker-sa-key
            items:
              - key: key.json
                path: key.json
